#!/usr/bin/bash


mysql -uroot -proot snc -e'load data LOCAL infile "snc_voice.csv" into table snc_voice fields terminated by "," lines terminated by "\n" ( Sl_NO ,
assetID ,
siteID ,
siteLID ,
inventory_id ,
order_id ,
product_id ,
manufacturer ,
Equipment_Type_New  ,
Model_Number  ,
product_description ,
Compliance_Status ,
Compliance_Status_Remarks ,
equipment_type ,
model_number   ,
OLD_assetManufacturer ,
OLD_assetModelNumber ,
OLD_assetPartNumber ,
assetHostName       ,
assetIPAddress      ,
assetSerialNumber ,
assetHoneywellAssetTag ,
assetVendorAssetTag ,
assetOperatingSystem ,
assetOSVersionLevel ,
assetSoftwareUpgradeDate ,
assetAssetType ,
assetAssetStatus ,
assetAge ,
assetBuilding ,
assetFloor ,
assetRoom ,
assetRack ,
assetRackPositions ,
assetDescIP ,
assetFeature ,
assetDesc ,
asset_name ,
mod_dt ,
rec_create_src ,
cascaded ,
ipt ,
usage_status ,
last_modified_by ,
proposed_cost_current_support ,
proposed_cost_new_support ,
proposed_cost_engineering_support ,
actual_cost_current_support ,
actual_cost_new_support ,
actual_cost_engineering_support ,
proposed_cost_hardware ,
actual_cost_hardware ,
Clarifications_Required ,
spare1 ,
spare2 ,
spare3 ,
spare4 

)';
